#!/bin/bash
port=$(date +"%I%S")
mongo_host=192.168.1.80
api_youtube_key=AIzaSyDNli7U6XFRiBCIxClMRPkObGvrm9Fxc6c
current_path=$(pwd)
sudo chown -R hieutct:hieutct $current_path
sudo rm -rf $current_path/.env
echo "TYPE=ytb
IP_ADDRESS=localhost
PORT=$port
NUM_CLIENT=10
CLIENT_TYPE=fb
API_YTB_KEY=$api_youtube_key
MONGO_HOST=$mongo_host
MONGO_DATABASE=crawler" >> $current_path/.env