#!/bin/bash

usage() { echo "Usage: $0 [-p <port>]" 1>&2; exit 1; }

while getopts ":p:" o; do
    case "${o}" in
        p)
            port=${OPTARG}
            ;;
        *)
            echo usage
    esac
done
shift $((OPTIND-1))

if [ -z "${port}" ]; then
    usage
fi

sudo kill -9 $(lsof -t -i:$port)
python3.5 -u servercommand.py port=$port >> Log/servercommand.log 2>&1