#!/bin/bash
echo -e "WELCOME TO CRAWLER LINK BOT"
echo -e "Server is runnning \e[0m...\e[0m"
echo -e "Run command view log server \"\e[1mtail -f Log/serversocket.log\e[0m\""
python3.5 -u serversocket.py >> Log/serversocket.log 2>&1