#!/bin/bash
Script/serversocket &
sleep 2
Script/clientsocket -t FB -l fb-socket &
sleep 2
Script/clientsocket -t IG -l ins-socket &
sleep 2
Script/clientsocket -t YT -l ins-socket &
sleep 2
Script/servercommand -p 8080 &
